name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore ./src/ApiUtc/ApiUtc.csproj

      - name: Build
        run: dotnet build ./src/ApiUtc/ApiUtc.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish ./src/ApiUtc/ApiUtc.csproj -c Release -o ./artifacts --no-build

  # -------- Opção A: publicar no GHCR usando o GITHUB_TOKEN (sem PAT) --------
  container-ghcr:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write   # necessário para publicar em ghcr.io usando github.token
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR (com GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build & Push (Ubuntu base)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/api-utc:10.0

      - name: Build & Push (Alpine base)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.alpine
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/api-utc:10.0-alpine

  # -------- Opção B: publicar usando um PAT em secret GHCR_TOKEN --------
  container-ghcr-pat:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ secrets.GHCR_TOKEN != '' }}    # só roda se você criar o secret GHCR_TOKEN
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR (com PAT)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push (Ubuntu base)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true   # aqui não precisa de expressão; o job todo já está condicionado no if
          tags: |
            ghcr.io/${{ github.repository_owner }}/api-utc:10.0

      - name: Build & Push (Alpine base)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.alpine
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/api-utc:10.0-alpine

